from setuptools import setup, find_packages

setup(
    name='wrappers',
    version='0.1.9'
    packages=find_packages(),
    install_requires=[
        'dependency1',
        'dependency2',
        'numpy',
        'pandas',
        'requests',
        'matplotlib',
        'scipy',
        'scikit-learn',
        'tensorflow',
        'torch',
        'flask',
        'django',
        'sqlalchemy',
        'beautifulsoup4',
        'pyyaml',
        'pytest',
        'coverage',
        'pytest-cov',
        'tox',
        'sphinx',
        'sphinx-rtd-theme',
        'wheel',
        'setuptools',
        'twine',
    ],
    author='Nadhiya D',
    author_email='nadhiyad.05@gmail.com',
    description='Installation setup for wrappers project',
    url='https://github.com/nadhiyad/Amazon_review',
    license='MIT',
)